### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by milandzuris** [Radioh/ha_twitch_helix#23]
Error every time when HA start

Logger: homeassistant.components.sensor
Source: custom_components/twitch_helix/sensor.py:156
Integration: Sensor (documentation, issues)
First occurred: 20:12:58 (2 occurrences)
Last logged: 20:12:58

twitch_helix: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await coro
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/twitch_helix/sensor.py", line 156, in update
    broadcast_user = broadcast_users["data"][0]
IndexError: list index out of range

**Comment by Radioh** [comment]
I'm thinking it is one the streamers it is not able to find. Maybe you should double check if the ones you have added in config.
I'm making an upgrade to the newest Twitch API version. In that update I'm handling this part of the code differently. If it fails it will result in a log message, where you can see what streamer it is failing on retrieving.

**Comment by Radioh** [comment]
Check out V. 1.0.0 - https://github.com/Radioh/ha_twitch_helix/releases/tag/v.1.0.0 
And see if you get some more info in the log. I'll close this issue.
